### ISSUE TITLE
[FE] 질문사항

### ISSUE THREAD

**Issue by youjinDev** [CodingOnTeamBook/Rebook_React_Node#94]
# Q1
searchPage에서 `useCheck` 사용하신거 봤는데, 책으로 검색/리뷰어 검색하는 버튼 상태값이 둘 다 true true로 되는 시점이 있어서 두 번씩 클릭해야 하는 버그가 있는 거 같습니다.
이거 그냥 토글 버튼으로 만들어서 state 하나만 쓰는 게 어떨까요?

```
const [typeA, setTypeA] = useState<boolean>(true);
const [typeB, setTypeB] = useState<boolean>(false);
```
현재 이렇게 되어있는데 이걸 상태 하나로 관리하는게 어떨까요? 아니면 다른 좋은 방법이 있으면 의견 주세요~

# Q2
리뷰 디테일 페이지에 댓글 작성 기능도 있어서 데이터 가져오고 보내는 작업 모두 리덕스로 할까 하는데 이렇게 작업해도 괜찮을까요? 🤔

**Comment by hi-jade88** [comment]
q1. searchPage는 버튼으로 수정해서 작업 하는 것이 좋을 것 같고, 그렇게 해서 default 값은 책 검색,  그리고 toggle 했을 때 리뷰어로 검색 할 수 있도록 하면 될 것 같습니다. 
Q2. 댓글 작성 기능은 depth 깊이가 깊지 않아서 그대로 props로 사용해도 될 것 같은데, 댓글 값을 계속 유지 해야 할 필요가 있다고 느껴지면 리덕스 쓰셔도 됩니다.
그런데 리덕스 쓰면 댓글 작성하고 다시 본 화면으로 나왔을 때도 계속 리덕스에 댓글 list를 가지고 있는 건데 굳이..? 라는 의문이 살짝 들어요.
그런데 리뷰 디테일 페이지에서 댓글 component까지 가는 깊이가 너무 깊으면 리덕스에 올리는게 나아요.

**Comment by reemrev21** [comment]
아.. 그러네요.. 일단 리덕스 사용하지 않고 작성해보고 댓글 component 까지 가는 깊이가 깊어지면 리덕스로 변경하도록 하겠습니다.
